const Joi = require("joi");
const { commonValidators } = require("../../utils");

module.exports = {
  paramId: commonValidators.paramId,

  create: Joi.object({
    body: Joi.object({
      name: Joi.string().required(),
      status: Joi.string().required(),
      position: Joi.string().required(),
      bonus: Joi.string().required(),
      bonus_percent: Joi.string().required(),
      bonus_from: Joi.string().required(),
      salary: Joi.number().required(),
      salaryPerHour: Joi.number().required(),
      salaryOverTimePerHour: Joi.number().required(),
      nationality: Joi.string().required(),
      dob: Joi.date().required(),
      telephone: Joi.string().required(),
      mobile: Joi.string().required(),
      email: Joi.string().required(),
      sex: Joi.string().required(),
      emp_type: Joi.string().required(),
      joining_date: Joi.date().required(),
      visa_status: Joi.string().required(),
      visa_expiry: Joi.date().required(),
      passport_no: Joi.string().required(),
      passport_issue: Joi.date().required(),
      passport_expiry: Joi.date().required(),
      labor_cardno: Joi.string().required(),
      labor_issue: Joi.date().required(),
      labor_expiry: Joi.date().required(),
      remind_before: Joi.number().required(),
      created_by: Joi.string().required(),
      created_date: Joi.date().required(),
      EmployeeCard_No: Joi.string().required(),
      Commission_Collected_Invoice_Flag: Joi.boolean().required(),
      Opening_Balance: Joi.number().required(),
      Opening_Balance_Date: Joi.date().required(),
      Department_Id: Joi.number().required(),
      IsCoordinator: Joi.boolean().required(),
      IsManager: Joi.boolean().required(),
      FAV: Joi.boolean().required(),
    }).required(),
  }),

  update: Joi.object({
    params: Joi.object({
      id: Joi.number().required(),
    }).required(),
    body: Joi.object({
      name: Joi.string(),
      status: Joi.string(),
      position: Joi.string(),
      bonus: Joi.string(),
      bonus_percent: Joi.string(),
      bonus_from: Joi.string(),
      salary: Joi.number(),
      salaryPerHour: Joi.number(),
      salaryOverTimePerHour: Joi.number(),
      nationality: Joi.string(),
      dob: Joi.date(),
      telephone: Joi.string(),
      mobile: Joi.string(),
      email: Joi.string(),
      sex: Joi.string(),
      emp_type: Joi.string(),
      joining_date: Joi.date(),
      visa_status: Joi.string(),
      visa_expiry: Joi.date(),
      passport_no: Joi.string(),
      passport_issue: Joi.date(),
      passport_expiry: Joi.date(),
      labor_cardno: Joi.string(),
      labor_issue: Joi.date(),
      labor_expiry: Joi.date(),
      remind_before: Joi.number(),
      created_by: Joi.string(),
      created_date: Joi.date(),
      EmployeeCard_No: Joi.string(),
      Commission_Collected_Invoice_Flag: Joi.boolean(),
      Opening_Balance: Joi.number(),
      Opening_Balance_Date: Joi.date(),
      Department_Id: Joi.number(),
      IsCoordinator: Joi.boolean(),
      IsManager: Joi.boolean(),
      FAV: Joi.boolean(),
    }).required(),
  }),

  getAll: Joi.object({
    query: Joi.object({
      ...commonValidators.pagination,

    }),
  }),
};
